name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Check (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build_tool: cargo
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            build_tool: cross
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            build_tool: cross
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            build_tool: cross
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            build_tool: cargo

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust target
      if: matrix.build_tool == 'cargo'
      run: rustup target add ${{ matrix.target }}
    - name: Install cross
      if: matrix.build_tool == 'cross'
      uses: taiki-e/install-action@cross
    - name: Check source
      run: ${{ matrix.build_tool }} check --locked --all-targets --target ${{ matrix.target }}
    - name: Run tests
      run: ${{ matrix.build_tool }} test --locked --target ${{ matrix.target }}

